// (1)
// a) Create Database
conn = new Mongo();
db = conn.getDB("NBADApp");
//
// // b) Add collections to the database.
db.createCollection("connection",{autoIndexId: false});
db.createCollection("user",{autoIndexId: false});
db.createCollection("userConnection",{autoIndexId: false});

// (2) Populate Database
// a) populate connection collection
db.connection.insertMany([{connId: "CON01", connName: "Smile, Please ;)", connTopic: "Happy Good Time : Recreational", connDetails: "This is an event designed for people who want to make memories by clicking group pictures with their loved ones. In this event you will get one minute and a lot of different props. There will be an automated machine which clicks several pictures with 5 seconds intervals between each click. You should pick your prop and get ready to pose for the picture in these intervals. In the end a video clip and a series of pictures will be printed and given to you.", connTime: "Friday, September 27, 2019|5:30pm - 6:30pm", Host: "Stacy MClean", location: "Cameron Auditorium, 1st Floor", userId: "102"},
{connId: "CON02", connName: "The Walkie Talkies", connTopic: "Happy Good Time : Recreational", connDetails: "This is an event designed for the people who want to have a healthy lifestyle. In this event random groups will be generated based on the list of registrations. People in the same group who are unknown to each other will be given a task just to get to know each other. This task might consists of relays or a treasure hunt which in turn will make you burn your calories.", connTime: "Wednesday, November 27, 2019|2:30pm - 3:30pm", Host: "Stacy MClean", location: "W203 Woodward Hall, 2nd Floor", userId: "102"},
{connId: "CON03", connName: "The Chamber of Secrets", connTopic: "Happy Good Time : Recreational", connDetails: "This is an event designed for people who are a die hard fan of Harry Potter series. In this event a Harry Potter movie will be shown to the people and after that a discussion will be help. The discussion topic will be based on an event shown in the movie. Refreshments will be provided in between to keep you charged throughout the session.", connTime: "Thursday, November 7, 2019|4:00pm - 6:30pm", Host: "Stacy MClean", location: "Jamie Lannister Room, 4th Floor", userId: "102"},
{connId: "CON04", connName: "No pain, No Gain!", connTopic: "Happy Good Time : Recreational", connDetails: "This is an event designed for people who are fitness freaks. In this event, different different exercise forms will be taught. Exercises will incorporate gym exercises, zumba, pilates, kick boxing, yoga etc. Energy drinks will be provided in between sessions to keep keep you hydrated throughout the event.", connTime: "Monday, December 2, 2019|12:30pm - 2:30pm", Host: "Andy Beudoin", location: "Danaerys Open Space, 1st Floor", userId: "101"},
{connId: "CON05", connName: "404 Not Found!", connTopic: "TechnoBuzz : Technical Know-how", connDetails: "This is a workshop designed for people who want to learn basics of HTTP. In this workshop along with the basics of HTTP you will learn how to implement various HTTP Request methods and everything you need to know about HTTP Response codes.", connTime: "Tuesday, January 27, 2020|9:00am - 10:30am", Host: "Andy Beudoin", location: "Aegon Auditorium, 2nd Floor", userId: "101"},
{connId: "CON06", connName: "The Magic of Map Filter Reduce", connTopic: "TechnoBuzz : Technical Know-how", connDetails: "This is a workshop designed for people who want to learn the basics of Map Filter Reduce and its real life applications. The workshop will take a closer look at these big three list operations and also provide some hand-on exercises experience to everyone whoever is registered for the event.", connTime: "Friday, February 15, 2020|11:30am - 12:30pm", Host: "Andy Beudoin", location: "Movida Room, 1st Floor", userId: "101"},
{connId: "CON07", connName: "MAD World", connTopic: "TechnoBuzz : Technical Know-how", connDetails: "This is a workshop designed for people who are interested in learning mobile application development from scratch. In this workshop you will learn all of the basic thing which help you to make a mobile application fully functional. In the end, you will be given a small project which would cover all of the concepts which were covered in the workshop session.", connTime: "Saturday, March 29, 2020|5:30pm - 6:30pm", Host: "Stacy MClean", location: "Jane M Auditorium, 1st Floor", userId: "102"},
{connId: "CON08", connName: "Catch Me If You Can", connTopic:"TechnoBuzz : Technical Know-how", connDetails:"This is a workshop designed for people who want to learn the basics of ethical hacking. Also, in this workshop you will learn the networking concepts which are important in order to learn ethical hacking. You will be given a demo of how to hack a simple site.  ", connTime:"Monday, April 11, 2020|3:30pm - 4:00pm", Host: "Andy Beudoin", location: "Cajun Hall, 5th Floor", userId: "101"}]);

// b) populate user collection
db.user.insertMany([{userId: "101", firstName: "Andy", lastName: "Beudoin", emailId: "abeudoin1223@gmail.com",add1: "786 Miller Dr.", add2: "Apt C",city: "Vienna",state: "VA",zipCode: "27651",country: "United States", username: "andy212", password: "1316cc6da09a4d9f66db889ada615bdfc9937e0166edd793ccb387d05df376965a00dd894d0a6e11c49f6c79ee4afab708dcc430eb60e46d81ece56be7370285"},
{userId: "102", firstName: "Stacy", lastName: "MClean", emailId: "stacy1223@gmail.com",add1: "1003 Botanical Dr.", add2: "Apt F",city: "Columbus",state: "OH",zipCode: "67575",country: "United States" ,username: "stacee28", password: "c15b1ac07cb7ead25f5be201cea16807753c528fc05a0b852efdf722ac033874185f1adb63ceae4d186e9970528b4f483143b02fa7c666cf01f5a745574d0678"}]);

conn = null;
